name: terraform-fmt
on:
  push:
    branches: [latest]
  pull_request:
jobs:
  terraform-fmt:
    name: Run terraform fmt checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: hashicorp/setup-terraform@v1
      - name: terraform-fmt
        run: terraform fmt -check -diff -recursive
